### ISSUE TITLE
Reconstruir el Modelo de la base de datos.

### ISSUE THREAD

**Issue by BrayanB24** [udistrital/polux_crud#30]
Basado en los modelos del Api crud polux_crud , reconstruir el modelo de la base de datos.

En caso de obtenerse el modelo por fuente de algún miembro de la oficina, documentar esto ( no se sube el modelo)

**Comment by BrayanB24** [comment]
Se obtuvo el modelo de la base de datos, se espera a hacer la revisión completa de las API para conocer si se hace uso de todas las tablas para estudiar su posible segmentación

**Comment by BrayanB24** [comment]
Se deberá estudiar a profundidad si el modelo obtenido se puede segmentar, el proyecto polux queda en StandBy y el modelo lo proporciona el entorno de desarrollo obtenido del anterior desarrollador.

**Comment by BOTOOM** [comment]
El modelo se puede visualizar usando el entorno de desarrollo en docker , mediante schemaspy
