### ISSUE TITLE
Solución de Error en usuario con rol: coordinador de pregrado

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_crud#37]
Se requiere solucionar error asociado a un usuario con rol de **coordinador de pregrado** el cual presenta la siguiente inconsistencia:

- Muestra el ID de usuario en el cliente.

**Criterio de aceptación**

- [ ] Solución del error.

Nota: el problema detallado se muestra en el [Issue 104](https://github.com/udistrital/polux_cliente/issues/104).

**Comment by mantnicot** [comment]
Se busco el error de parte del código para intentar ver si el fallo es de código pero se ve bien el funcionamiento correcto, se asume que el problema es del sistema de autenticación o guardado de la informacion del id del usuario :+1: 

Arte danzario
51722992 coordinadorarte MARTHA ESPERANZA OSPINA ESPITIA meospinae

![Captura de pantalla de 2021-07-30 17-31-03](https://user-images.githubusercontent.com/85162258/127717869-0bbe2f89-5345-416c-a2fe-d2f30e99950a.png)


Se ve que el programa solo llama la información y la muestra, más no la trabaja

Se recomienda ver la BD, todavía no se puede ver por el problema de VPN
